### ISSUE TITLE
Change mouse to arrows when able to resize

### ISSUE THREAD

**Issue by WebFreak001** [gedaiu/tested-atom#2]
With console output you cant really read anything because all the important output is out of the panel. Making it resizable would help

**Comment by WebFreak001** [comment]
Edit: Just found out you could resize but the mouse does not indicate so (on windows)

**Comment by gedaiu** [comment]
sorry... i never tested the plugin on windows :).. is this fixed?

**Comment by WebFreak001** [comment]
yeah i added it to the pr

**Comment by gedaiu** [comment]
thx
